// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0UzTNMBeJgrpOHMqIrs5Wr1OCuBeQnZc',
    appId: '1:629113610146:web:21ff19a7eee7ade6429cfb',
    messagingSenderId: '629113610146',
    projectId: 'test-app-2177e',
    authDomain: 'test-app-2177e.firebaseapp.com',
    storageBucket: 'test-app-2177e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZNv62Hwi4HInrz0LPqSoIhGHVxgEchU',
    appId: '1:629113610146:android:efdef1a0e2fc7144429cfb',
    messagingSenderId: '629113610146',
    projectId: 'test-app-2177e',
    storageBucket: 'test-app-2177e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANk7nVDz8YlhYUPlzcnQrpcFgajr--d7w',
    appId: '1:629113610146:ios:199e87d50a9d2c2c429cfb',
    messagingSenderId: '629113610146',
    projectId: 'test-app-2177e',
    storageBucket: 'test-app-2177e.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANk7nVDz8YlhYUPlzcnQrpcFgajr--d7w',
    appId: '1:629113610146:ios:199e87d50a9d2c2c429cfb',
    messagingSenderId: '629113610146',
    projectId: 'test-app-2177e',
    storageBucket: 'test-app-2177e.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0UzTNMBeJgrpOHMqIrs5Wr1OCuBeQnZc',
    appId: '1:629113610146:web:0db86b6b14427ee9429cfb',
    messagingSenderId: '629113610146',
    projectId: 'test-app-2177e',
    authDomain: 'test-app-2177e.firebaseapp.com',
    storageBucket: 'test-app-2177e.appspot.com',
  );

}